function [BW,maskedImage] = segmentImage(RGB)
%segmentImage Segment image using auto-generated code from imageSegmenter App
% [BW,MASKEDIMAGE] = segmentImage(RGB) segments image RGB using
% auto-generated code from the imageSegmenter App. The final segmentation
% is returned in BW, and a masked image is returned in MASKEDIMAGE.
 
% Auto-generated by imageSegmenter app on 21-Jul-2018
%----------------------------------------------------
 
% Convert RGB image into L*a*b* color space.
X = rgb2lab(RGB);
 
% Graph Cut
foregroundInd = [2934150 3025838 4323953 4389272 4428452 4441522 4441527 4454632 4478152 4491256 4504326 4504361 4517451 4517476 4517500 4517540 4517555 4517575 4517590 4517595 4543730 5802341 5828471 5838971 5838986 5852060 5852070 5852125 5852130 5852150 5852170 5852180 5852185 5852195 7722421 7722426 7735456 7800269 8616438 8629458 8629468 8655519 8655539 8681604 8707674 8733615 8733749 ];
backgroundInd = [869446 947905 ];
L = superpixels(X,30326,'IsInputLab',true);
 
% Convert L*a*b* range to [0 1]
scaledX = X;
scaledX(:,:,1) = X(:,:,1) / 100;
scaledX(:,:,2:3) = (X(:,:,2:3) + 100) / 200;
BW = lazysnapping(scaledX,L,foregroundInd,backgroundInd);
 
% Create masked image.
maskedImage = RGB;
maskedImage(repmat(~BW,[1 1 3])) = 0;
